import React from "react";
import { RefreshCw, Download } from "lucide-react";
import { useRepository } from "./RepositoryContext";

export function AnalysisHeader() {
  const { activeResult, isScanning, triggerAnalysis } = useRepository();

  const handleExport = () => {
    if (!activeResult) return;

    const codeLangs = activeResult.languages?.map((l) => l.name).join(", ") || "N/A";
    const dateStr = new Date().toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const mdContent = `# DevPilot AI Report: ${activeResult.name}

## 📊 Overview
- **Summary:** ${activeResult.description || "A software development project."}
- **Tech Stack:** ${codeLangs}
- **Project Activity:** ${activeResult.stars || 0} ⭐ / ${activeResult.forks || 0} 🍴
- **Main Purpose / Audience:** ${activeResult.metadataAnalysis?.audience || "Developers"}

## 🏗️ Architecture
- **High-level Layout:** ${activeResult.overallHealth?.summary || "Standard project footprint."}
- **Entry Points:** ${(activeResult.entryPoints || []).map((e) => `\`${e}\``).join(", ") || "N/A"}
- **Core Complexity:** ${activeResult.learningComplexity?.reason || "Typical backend/frontend mechanics."}

## 🛣️ Learning Roadmap (Step-by-Step)
${
  (activeResult.roadmap || [])
    .map(
      (r, i) => `### Phase ${i + 1}: ${r.title}
- **Estimated Time:** ${r.estimatedTime}
- **Focus:** ${r.description}`,
    )
    .join("\n\n") || "No guided roadmap detected for this repository."
}

## ⚕️ Health & Recommendations
- **Overall Health:** ${activeResult.healthScore}/100 (${activeResult.overallHealth?.scoreLabel || "Good"})
- **Static Metrics:** Documentation (${activeResult.healthMetrics?.documentation}/100), Code Quality (${activeResult.healthMetrics?.codeQuality}/100), Testing (${activeResult.healthMetrics?.testing}/100)

### Actionable Improvements
${(activeResult.healthRecommendations || []).map((rec) => `- **[${rec.severity.toUpperCase()}] ${rec.title}:** ${rec.description}`).join("\n") || "- Architecture seems well established. Ensure lockfiles are updated."}

## 🔍 Key Files & What They Do
${
  (activeResult.entryPoints || [])
    .slice(0, 8)
    .map((file) => `- \`${file}\`: Core execution or initialization hook.`)
    .join("\n") || "- Navigate the `src` directory for primary execution logic."
}

## 💡 Quick Start & Tips
**How to run locally:**
${(Array.isArray(activeResult.localSetup?.steps) ? activeResult.localSetup!.steps : []).map((step: { command?: string; description?: string }, i: number) => `${i + 1}. \`${step.command || step}\` - ${step.description || ""}`).join("\n") || "1. Install standard dependencies\n2. Run the development server (e.g., `npm run dev` or `docker-compose up`)"}

## 📈 Generated by DevPilot AI
- **Date:** ${dateStr}
- **Link:** https://devpilot-ai.vercel.app`;

    const blob = new Blob([mdContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${activeResult.name}-audit.md`;
    a.click();
  };

  return (
    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-border/40 pb-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">Analyze Repository</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Map files, dependencies, entry points, and generate an interactive onboarding roadmap.
        </p>
      </div>
      {activeResult && !isScanning && (
        <div className="flex items-center gap-3">
          <button
            onClick={handleExport}
            className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-border bg-secondary px-4 text-xs font-medium text-secondary-foreground hover:bg-secondary/80 transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary"
            aria-label="Export Markdown Report"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Export Report</span>
          </button>
          <button
            onClick={() => triggerAnalysis(activeResult.repoUrl)}
            className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-border bg-card px-4 text-xs font-medium text-foreground hover:bg-muted transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary"
            aria-label="Re-analyze repository"
          >
            <RefreshCw className="h-3.5 w-3.5 text-primary" />
            <span>Re-Analyze</span>
          </button>
        </div>
      )}
    </div>
  );
}
export default AnalysisHeader;
